/*
 * Copyright (C) 2016 Frank Hossfeld <frank.hossfeld@googlemail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package de.gishmo.gwt.example.mvp4g2.springboot.client;


import com.google.gwt.core.client.EntryPoint;

/**
 * Entry point classes define <code>onModuleLoad()</code>.
 */
public class Mvp4g2SpringBoot
  implements EntryPoint {
  /**
   * <p>This is the entry point method.</p>
   * <p></p>
   */
  public void onModuleLoad() {
    // Create the application.
    // The Mvp4g2SprinbgBootApplicationImpl-class
    // will be generated by the framework.
    Mvp4g2SprinbgBootApplication application = new Mvp4g2SprinbgBootApplicationImpl();
    // start the applictaion by calling the run()-method.
    application.run();
  }
}
